# Generated by Django 6.0 on 2026-01-03 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0003_dailyentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='LibraryPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon', models.CharField(default='bx-dumbbell', max_length=50)),
                ('plan_type', models.CharField(default='Силовой', max_length=50)),
                ('days', models.CharField(default='3 дня', max_length=20)),
                ('level', models.CharField(default='Новичок', max_length=20)),
                ('schedule', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='SharedPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=12, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('schedule', models.JSONField()),
            ],
        ),
    ]
