# Generated by Django 6.0 on 2026-01-03 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0004_libraryplan_sharedplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='subscription_end',
            field=models.DateField(blank=True, null=True),
        ),
    ]
